# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        name: bandit - Checks for vulnerabilities
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      # Run ruff linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run ruff formatter.
      - id: ruff-format
        types_or: [ python, pyi ]